# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('boss', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Job'),
        ),
    ]
