# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employe_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employe',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Job'),
        ),
    ]
