# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190111_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='bearer_token',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
