# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190120_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='bearer_token',
            field=models.CharField(default='0', max_length=2000),
        ),
    ]
