# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190120_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='token_expire_on',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
